const express = require('express');
const cors = require('cors');
const ngrok = require('ngrok'); // Ensure ngrok is installed
const app = express();
const port = process.env.PORT || 8000;

// Set this to true to use ngrok, false to use the local port
const useNgrok = false; // Toggle this value

const corsOptions = {
  origin: '*', 
  methods: 'GET,POST,PUT,DELETE,OPTIONS', // Include all necessary methods
  allowedHeaders: 'Content-Type,Authorization,X-Requested-With,Origin,Accept',
  optionsSuccessStatus: 200, // Some legacy browsers (IE11, various SmartTVs) choke on 204
};

app.options('*', cors(corsOptions)); 
app.use(express.json());

// Middleware to log requests
app.use((req, res, next) => {
  console.log('Received request on', req.path);
  console.log('Request Method:', req.method);
  console.log('Request Headers:', JSON.stringify(req.headers, null, 2));
  console.log('Request Body:', JSON.stringify(req.body, null, 2));
  console.log('Request Query:', JSON.stringify(req.query, null, 2));
  next();
});

app.get('/overrides', (req, res) => {
  res.send({
    themeV2: {
      loginBox:{
        pageFooter: `
            <div style="text-align: center; padding: 10px;">
              <label style="display: flex; align-items: center; gap: 8px; padding: 5px 10px; border: 1px solid #ccc; border-radius: 4px; background-color: #ffffff; cursor: pointer;">
                <select style="border: none; font-size: 14px; outline: none;" onchange="(function(selectedValue) {
                  const languageMap = {
                    'en': 'English',
                    'es': 'Spanish',
                    'de': 'German',
                    'fr': 'French',
                    'it': 'Italian'
                  };
                  localStorage.setItem('frontegg-language', selectedValue);
                  console.log('Language updated to:', languageMap[selectedValue]);
                  location.reload();
                })(this.value)">
                  <option value="en">🇬🇧 English</option>
                  <option value="es">🇪🇸 Spanish</option>
                  <option value="de">🇩🇪 German</option>
                  <option value="fr">🇫🇷 French</option>
                  <option value="it">🇮🇹 Italian</option>
                </select>
              </label>
              <script>
                document.addEventListener('DOMContentLoaded', function() {
                  const savedLanguage = localStorage.getItem('frontegg-language') || 'en';
                  document.querySelector('select').value = savedLanguage;
                });
              </script>
            </div>
          `,
      },
    },
    localizations: {
      en: {
        loginBox: {
          login: {
            title: "Sign In",
            signUpMessage: "Don't have an account? Sign up here.",
            signUpLink: "Create a new account",
            forgotPassword: "Forgot your password?",
            emailInputLabel: "Email Address",
            emailInputPlaceholder: "name@example.com",
            emailMustBeValid: "Please enter a valid email address.",
            emailIsRequired: "Email address is required.",
            passwordInputLabel: "Password",
            passwordInputPlaceholder: "Enter your password",
            passwordMustBeCharacters: "Password must be at least 8 characters.",
            passwordIsRequired: "Password is required.",
            login: "Log In",
            continue: "Continue",
            invalidTitle: "Invalid Login Attempt",
            signInWithSocialLogin: "Or sign in with:",
            backToLogin: "Back to login",
            mfaTitle: "Multi-Factor Authentication",
            mfaSubtitle: "Please enter the code sent to your device.",
            mfaAuthenticatorTitle: "Authenticator Code",
            mfaInputLabel: "Enter MFA Code",
            mfaCodeIsRequired: "MFA code is required.",
            mfaCodeLengthAtLeast6: "MFA code must be at least 6 digits.",
            twoFactorCodeIsRequired: "Two-factor code is required.",
            twoFactorCodeLengthAtLeast8: "Two-factor code must be at least 8 digits.",
            mfaRememberThisDevice: "Remember this device for future logins.",
            mfaRememberLongerThenYear: "Keep me logged in for a year or more.",
            disableMultiFactorTitle: "Disable MFA",
            disableMultiFactorMessage: "Are you sure you want to disable multi-factor authentication?",
            recoverMfaTitle: "Recover Multi-Factor Authentication",
            recoverMfaMessage: "Enter your recovery code to regain access.",
            disabledMultiFactorClickHereButton: "Click here to recover MFA.",
            enterRecoveryCode: "Enter your recovery code",
            disabledMultiFactorButton: "Recover MFA",
            missingPolicyErrorMessage: "Your login policy is missing required configurations.",
            magicLinkTitle: "Magic Link Sent",
            magicLinkText: "Check your email to sign in using the magic link.",
            magicLinkResend: "Resend magic link",
            magicLinkResending: "Resending magic link...",
            invalidMagicLinkTitle: "Invalid Magic Link",
            invalidMagicLinkText: "The magic link you used is invalid or expired.",
            smsOtcTitle: "SMS One-Time Code",
            smsOtcMessage: "Please enter the one-time code sent to your phone.",
            smsOtcChangePhoneMessage: "Change your phone number?",
            otcTitle: "One-Time Code",
            otcMessage: "Enter the code sent to your device.",
            otcInputLabel: "Enter Code",
            otcInputPlaceholder: "123456",
            otcCodeIsRequired: "One-time code is required.",
            otcContinue: "Verify",
            otcHaventReceivedCode: "Didn't receive a code?",
            otcResend: "Resend Code",
            otcResending: "Resending code...",
            otcInvalidLengthCode: "The code must be exactly 6 digits.",
            ssoRedirectToMessage: "Redirecting to your SSO provider...",
            failedOicdLoginTitle: "Login Failed",
            failedOicdBackToLogin: "Back to login",
            failedSamlDefaultError: "There was an error during SAML login.",
            failedSamlBackToLogin: "Back to login",
            joinTenantTitle: "Join Organization",
            failedJoinTenantTitle: "Failed to Join Organization",
            failedJoinTenantBackButton: "Back to join screen",
            forceMfaTitle: "Enforce MFA",
            forceMfaMessage: "You must enable multi-factor authentication to proceed.",
            forceMfaScanQueryDescription1: "Scan the QR code with your authenticator app.",
            forceMfaScanQueryDescription2: "Then, enter the verification code to continue.",
            forceMfaInputLabel: "Enter Verification Code",
            forceMfaInputPlaceholder: "123456",
            forceMfaVerifyButton: "Verify",
            forceMfaRememberThisDevice: "Remember this device",
            forceMfaRememberLongerThenYear: "Keep me logged in for a year",
            disclaimerText: "I agree to the",
            termsLinkText: "Terms of Service",
            termsLink: "/terms",
            privacyLinkText: "Privacy Policy",
            privacyLink: "/privacy",
            termsAndPrivacyConjunctionText: "and",
            oneTouchLoginTitle: "One-Touch Login",
            oneTouchLoginMessage: "Sign in securely with one touch.",
            oneTouchLoginButton: "Use One-Touch Login",
            touchId: "Sign in with Touch ID",
            androidLoginTitle: "Android Login",
            androidLoginMessage: "Sign in securely using Android biometrics.",
            androidLoginButton: "Use Android Login",
            android: "Android",
            usbLoginTitle: "USB Security Key",
            usbLoginMessage: "Sign in with your USB security key.",
            usbLoginButton: "Use USB Security Key",
            usb: "USB",
            smsLoginTitle: "SMS Login",
            smsLoginMessage: "Sign in using a one-time code sent via SMS.",
            smsLoginButton: "Use SMS Login",
            sms: "SMS",
            smsLoginChangePhoneTitle: "Change Phone Number",
            smsLoginChangePhoneMessage: "Enter a new phone number to receive your SMS code.",
            smsLoginChangePhoneInputLabel: "New Phone Number",
            smsLoginChangePhoneButton: "Update Phone Number",
            smsLoginPinTitle: "SMS PIN",
            smsLoginPinMessage: "Enter the PIN sent to your phone.",
            smsLoginPinButton: "Submit PIN",
            loginWelcomeTitle: "Welcome Back!",
            loginWelcomeSubtitleSubtitle: "Securely log in to your account.",
            loginWelcomeKnownUserSubtitle: "Welcome, {username}! Ready to continue?",
            registerNewQuickLoginTitle: "Quick Login",
            registerNewQuickLoginTitleWithSocial: "Or register with your social account:",
            registerNewQuickLoginSubtitle: "Complete the quick registration process to get started.",
            phoneIsRequired: "Phone number is required.",
            phoneIsInvalid: "Phone number is invalid.",
            forceEnrollMfaTitle: "Enroll in MFA",
            forceEnrollMfaSubtitle: "You need to enable multi-factor authentication to continue.",
            forceEnrollMfaAuthenticatorApp: "Use an Authenticator App",
            forceEnrollMfaAuthenticatorAppDescription: "Scan the QR code with your authenticator app.",
            forceEnrollMfaSMS: "Use SMS",
            forceEnrollMfaPlatform: "Use Platform-Based Security",
            forceEnrollMfaCrossPlatform: "Cross-Platform MFA",
            forceEnrollMfaCrossPlatformDescription: "Sign in with a secure cross-platform method.",
            preEnrollMfaSMSTitle: "Enroll via SMS",
            preEnrollMfaSMSSubtitle: "Set up SMS-based multi-factor authentication.",
            preEnrollMfaSMSSubmitButtonMessage: "Submit",
            mfaSMSTitle: "SMS Multi-Factor Authentication",
            mfaSMSSubtitle: "Enter the code sent to your phone.",
            mfaSMSResendCode: "Resend code",
            enrollMfaSMSBackMessage: "Go back",
            moreWaysToAuthenticate: "More ways to authenticate",
            loginMfaSMS: "Login via SMS",
            loginMfaSMSDescription: "Enter the code sent to your phone.",
            loginMfaPlatform: "Use Platform Security",
            loginMfaPlatformDescription: "Sign in with platform-based security.",
            loginMfaCrossPlatform: "Cross-Platform MFA",
            loginMfaCrossPlatformDescription: "Sign in using cross-platform security.",
            loginMfaAuthenticatorApp: "Use Authenticator App",
            loginMfaAuthenticatorAppDescription: "Enter the code from your authenticator app.",
            loginMfaAuthenticatorAppTitle: "Authenticator App Login",
            loginMfaHelpMessage: "Need help with multi-factor authentication?",
            useRecoveryCode: "Use recovery code",
          }
        }
      },
      es: {
        loginBox: {
          login: {
            title: "Iniciar sesión",
            signUpMessage: "¿No tienes una cuenta? Regístrate aquí.",
            signUpLink: "Crear una nueva cuenta",
            forgotPassword: "¿Olvidaste tu contraseña?",
            emailInputLabel: "Dirección de correo electrónico",
            emailInputPlaceholder: "nombre@ejemplo.com",
            emailMustBeValid: "Por favor, introduce una dirección de correo válida.",
            emailIsRequired: "Se requiere dirección de correo electrónico.",
            passwordInputLabel: "Contraseña",
            passwordInputPlaceholder: "Introduce tu contraseña",
            passwordMustBeCharacters: "La contraseña debe tener al menos 8 caracteres.",
            passwordIsRequired: "Se requiere la contraseña.",
            login: "Iniciar sesión",
            continue: "Continuar",
            invalidTitle: "Intento de inicio de sesión inválido",
            signInWithSocialLogin: "O inicia sesión con:",
            backToLogin: "Volver al inicio de sesión",
            mfaTitle: "Autenticación de múltiples factores",
            mfaSubtitle: "Introduce el código enviado a tu dispositivo.",
            mfaAuthenticatorTitle: "Código del autenticador",
            mfaInputLabel: "Introduce el código MFA",
            mfaCodeIsRequired: "Se requiere el código MFA.",
            mfaCodeLengthAtLeast6: "El código MFA debe tener al menos 6 dígitos.",
            twoFactorCodeIsRequired: "Se requiere el código de dos factores.",
            twoFactorCodeLengthAtLeast8: "El código de dos factores debe tener al menos 8 dígitos.",
            mfaRememberThisDevice: "Recordar este dispositivo para futuros inicios de sesión.",
            mfaRememberLongerThenYear: "Mantenerme conectado por un año o más.",
            disableMultiFactorTitle: "Desactivar MFA",
            disableMultiFactorMessage: "¿Estás seguro de que deseas desactivar la autenticación de múltiples factores?",
            recoverMfaTitle: "Recuperar autenticación de múltiples factores",
            recoverMfaMessage: "Introduce tu código de recuperación para recuperar el acceso.",
            disabledMultiFactorClickHereButton: "Haz clic aquí para recuperar MFA.",
            enterRecoveryCode: "Introduce tu código de recuperación",
            disabledMultiFactorButton: "Recuperar MFA",
            missingPolicyErrorMessage: "Tu política de inicio de sesión carece de configuraciones necesarias.",
            magicLinkTitle: "Enlace mágico enviado",
            magicLinkText: "Revisa tu correo para iniciar sesión con el enlace mágico.",
            magicLinkResend: "Reenviar enlace mágico",
            magicLinkResending: "Reenviando enlace mágico...",
            invalidMagicLinkTitle: "Enlace mágico inválido",
            invalidMagicLinkText: "El enlace mágico que usaste es inválido o ha expirado.",
            smsOtcTitle: "Código SMS de un solo uso",
            smsOtcMessage: "Introduce el código de un solo uso enviado a tu teléfono.",
            smsOtcChangePhoneMessage: "¿Cambiar tu número de teléfono?",
            otcTitle: "Código de un solo uso",
            otcMessage: "Introduce el código enviado a tu dispositivo.",
            otcInputLabel: "Introduce el código",
            otcInputPlaceholder: "123456",
            otcCodeIsRequired: "Se requiere el código de un solo uso.",
            otcContinue: "Verificar",
            otcHaventReceivedCode: "¿No recibiste el código?",
            otcResend: "Reenviar código",
            otcResending: "Reenviando código...",
            otcInvalidLengthCode: "El código debe tener exactamente 6 dígitos.",
            ssoRedirectToMessage: "Redirigiendo a tu proveedor de SSO...",
            failedOicdLoginTitle: "Inicio de sesión fallido",
            failedOicdBackToLogin: "Volver al inicio de sesión",
            failedSamlDefaultError: "Hubo un error durante el inicio de sesión SAML.",
            failedSamlBackToLogin: "Volver al inicio de sesión",
            joinTenantTitle: "Unirse a la organización",
            failedJoinTenantTitle: "No se pudo unir a la organización",
            failedJoinTenantBackButton: "Volver a la pantalla de unión",
            forceMfaTitle: "Forzar MFA",
            forceMfaMessage: "Debes habilitar la autenticación de múltiples factores para proceder.",
            forceMfaScanQueryDescription1: "Escanea el código QR con tu aplicación autenticadora.",
            forceMfaScanQueryDescription2: "Luego, introduce el código de verificación para continuar.",
            forceMfaInputLabel: "Introduce el código de verificación",
            forceMfaInputPlaceholder: "123456",
            forceMfaVerifyButton: "Verificar",
            forceMfaRememberThisDevice: "Recordar este dispositivo",
            forceMfaRememberLongerThenYear: "Mantenerme conectado por un año",
            disclaimerText: "Estoy de acuerdo con los",
            termsLinkText: "Términos de servicio",
            termsLink: "/terminos",
            privacyLinkText: "Política de privacidad",
            privacyLink: "/privacidad",
            termsAndPrivacyConjunctionText: "y",
            oneTouchLoginTitle: "Inicio de sesión con un toque",
            oneTouchLoginMessage: "Inicia sesión de manera segura con un toque.",
            oneTouchLoginButton: "Usar inicio de sesión con un toque",
            touchId: "Iniciar sesión con Touch ID",
            androidLoginTitle: "Inicio de sesión en Android",
            androidLoginMessage: "Inicia sesión de manera segura usando la biometría de Android.",
            androidLoginButton: "Usar inicio de sesión en Android",
            android: "Android",
            usbLoginTitle: "Clave de seguridad USB",
            usbLoginMessage: "Inicia sesión con tu clave de seguridad USB.",
            usbLoginButton: "Usar clave de seguridad USB",
            usb: "USB",
            smsLoginTitle: "Inicio de sesión por SMS",
            smsLoginMessage: "Inicia sesión usando un código de un solo uso enviado por SMS.",
            smsLoginButton: "Usar inicio de sesión por SMS",
            sms: "SMS",
            smsLoginChangePhoneTitle: "Cambiar número de teléfono",
            smsLoginChangePhoneMessage: "Introduce un nuevo número de teléfono para recibir tu código SMS.",
            smsLoginChangePhoneInputLabel: "Nuevo número de teléfono",
            smsLoginChangePhoneButton: "Actualizar número de teléfono",
            smsLoginPinTitle: "PIN SMS",
            smsLoginPinMessage: "Introduce el PIN enviado a tu teléfono.",
            smsLoginPinButton: "Enviar PIN",
            loginWelcomeTitle: "¡Bienvenido de nuevo!",
            loginWelcomeSubtitleSubtitle: "Inicia sesión de manera segura en tu cuenta.",
            loginWelcomeKnownUserSubtitle: "¡Bienvenido, {username}! ¿Listo para continuar?",
            registerNewQuickLoginTitle: "Inicio de sesión rápido",
            registerNewQuickLoginTitleWithSocial: "O regístrate con tu cuenta social:",
            registerNewQuickLoginSubtitle: "Completa el proceso rápido de registro para comenzar.",
            phoneIsRequired: "Se requiere número de teléfono.",
            phoneIsInvalid: "El número de teléfono es inválido.",
            forceEnrollMfaTitle: "Inscribirse en MFA",
            forceEnrollMfaSubtitle: "Debes habilitar la autenticación de múltiples factores para continuar.",
            forceEnrollMfaAuthenticatorApp: "Usar una aplicación autenticadora",
            forceEnrollMfaAuthenticatorAppDescription: "Escanea el código QR con tu aplicación autenticadora.",
            forceEnrollMfaSMS: "Usar SMS",
            forceEnrollMfaPlatform: "Usar seguridad basada en plataforma",
            forceEnrollMfaCrossPlatform: "MFA multiplataforma",
            forceEnrollMfaCrossPlatformDescription: "Inicia sesión de manera segura con un método multiplataforma.",
            preEnrollMfaSMSTitle: "Inscribirse vía SMS",
            preEnrollMfaSMSSubtitle: "Configura la autenticación de múltiples factores basada en SMS.",
            preEnrollMfaSMSSubmitButtonMessage: "Enviar",
            mfaSMSTitle: "Autenticación de múltiples factores por SMS",
            mfaSMSSubtitle: "Introduce el código enviado a tu teléfono.",
            mfaSMSResendCode: "Reenviar código",
            enrollMfaSMSBackMessage: "Volver",
            moreWaysToAuthenticate: "Más formas de autenticarte",
            loginMfaSMS: "Iniciar sesión por SMS",
            loginMfaSMSDescription: "Introduce el código enviado a tu teléfono.",
            loginMfaPlatform: "Usar seguridad de plataforma",
            loginMfaPlatformDescription: "Inicia sesión con seguridad basada en plataforma.",
            loginMfaCrossPlatform: "MFA multiplataforma",
            loginMfaCrossPlatformDescription: "Inicia sesión usando seguridad multiplataforma.",
            loginMfaAuthenticatorApp: "Usar aplicación autenticadora",
            loginMfaAuthenticatorAppDescription: "Introduce el código de tu aplicación autenticadora.",
            loginMfaAuthenticatorAppTitle: "Inicio de sesión con aplicación autenticadora",
            loginMfaHelpMessage: "¿Necesitas ayuda con la autenticación de múltiples factores?",
            useRecoveryCode: "Usar código de recuperación",
          }
        }
      },
      fr: {
        loginBox: {
          login: {
            title: "Se connecter",
            signUpMessage: "Vous n'avez pas de compte? Inscrivez-vous ici.",
            signUpLink: "Créer un nouveau compte",
            forgotPassword: "Mot de passe oublié?",
            emailInputLabel: "Adresse e-mail",
            emailInputPlaceholder: "nom@exemple.com",
            emailMustBeValid: "Veuillez entrer une adresse e-mail valide.",
            emailIsRequired: "L'adresse e-mail est requise.",
            passwordInputLabel: "Mot de passe",
            passwordInputPlaceholder: "Entrez votre mot de passe",
            passwordMustBeCharacters: "Le mot de passe doit comporter au moins 8 caractères.",
            passwordIsRequired: "Le mot de passe est requis.",
            login: "Se connecter",
            continue: "Continuer",
            invalidTitle: "Tentative de connexion invalide",
            signInWithSocialLogin: "Ou connectez-vous avec:",
            backToLogin: "Retour à la connexion",
            mfaTitle: "Authentification à plusieurs facteurs",
            mfaSubtitle: "Veuillez entrer le code envoyé à votre appareil.",
            mfaAuthenticatorTitle: "Code d'authentificateur",
            mfaInputLabel: "Entrez le code MFA",
            mfaCodeIsRequired: "Le code MFA est requis.",
            mfaCodeLengthAtLeast6: "Le code MFA doit comporter au moins 6 chiffres.",
            twoFactorCodeIsRequired: "Le code à deux facteurs est requis.",
            twoFactorCodeLengthAtLeast8: "Le code à deux facteurs doit comporter au moins 8 chiffres.",
            mfaRememberThisDevice: "Se souvenir de cet appareil pour les futures connexions.",
            mfaRememberLongerThenYear: "Restez connecté pendant un an ou plus.",
            disableMultiFactorTitle: "Désactiver MFA",
            disableMultiFactorMessage: "Êtes-vous sûr de vouloir désactiver l'authentification à plusieurs facteurs?",
            recoverMfaTitle: "Récupérer l'authentification à plusieurs facteurs",
            recoverMfaMessage: "Entrez votre code de récupération pour récupérer l'accès.",
            disabledMultiFactorClickHereButton: "Cliquez ici pour récupérer MFA.",
            enterRecoveryCode: "Entrez votre code de récupération",
            disabledMultiFactorButton: "Récupérer MFA",
            missingPolicyErrorMessage: "Votre politique de connexion manque de configurations requises.",
            magicLinkTitle: "Lien magique envoyé",
            magicLinkText: "Vérifiez votre e-mail pour vous connecter en utilisant le lien magique.",
            magicLinkResend: "Renvoyer le lien magique",
            magicLinkResending: "Renvoi du lien magique...",
            invalidMagicLinkTitle: "Lien magique invalide",
            invalidMagicLinkText: "Le lien magique que vous avez utilisé est invalide ou a expiré.",
            smsOtcTitle: "Code à usage unique par SMS",
            smsOtcMessage: "Veuillez entrer le code à usage unique envoyé sur votre téléphone.",
            smsOtcChangePhoneMessage: "Changer votre numéro de téléphone?",
            otcTitle: "Code à usage unique",
            otcMessage: "Entrez le code envoyé à votre appareil.",
            otcInputLabel: "Entrez le code",
            otcInputPlaceholder: "123456",
            otcCodeIsRequired: "Le code à usage unique est requis.",
            otcContinue: "Vérifier",
            otcHaventReceivedCode: "Vous n'avez pas reçu de code?",
            otcResend: "Renvoyer le code",
            otcResending: "Renvoi du code...",
            otcInvalidLengthCode: "Le code doit comporter exactement 6 chiffres.",
            ssoRedirectToMessage: "Redirection vers votre fournisseur SSO...",
            failedOicdLoginTitle: "Échec de la connexion",
            failedOicdBackToLogin: "Retour à la connexion",
            failedSamlDefaultError: "Une erreur est survenue lors de la connexion SAML.",
            failedSamlBackToLogin: "Retour à la connexion",
            joinTenantTitle: "Rejoindre l'organisation",
            failedJoinTenantTitle: "Échec de la tentative de rejoindre l'organisation",
            failedJoinTenantBackButton: "Retour à l'écran de jonction",
            forceMfaTitle: "Forcer MFA",
            forceMfaMessage: "Vous devez activer l'authentification à plusieurs facteurs pour continuer.",
            forceMfaScanQueryDescription1: "Scannez le code QR avec votre application d'authentification.",
            forceMfaScanQueryDescription2: "Ensuite, entrez le code de vérification pour continuer.",
            forceMfaInputLabel: "Entrez le code de vérification",
            forceMfaInputPlaceholder: "123456",
            forceMfaVerifyButton: "Vérifier",
            forceMfaRememberThisDevice: "Se souvenir de cet appareil",
            forceMfaRememberLongerThenYear: "Restez connecté pendant un an",
            disclaimerText: "J'accepte les",
            termsLinkText: "Conditions d'utilisation",
            termsLink: "/termes",
            privacyLinkText: "Politique de confidentialité",
            privacyLink: "/confidentialite",
            termsAndPrivacyConjunctionText: "et",
            oneTouchLoginTitle: "Connexion en un seul clic",
            oneTouchLoginMessage: "Connectez-vous en toute sécurité avec un seul clic.",
            oneTouchLoginButton: "Utiliser la connexion en un clic",
            touchId: "Se connecter avec Touch ID",
            androidLoginTitle: "Connexion Android",
            androidLoginMessage: "Connectez-vous en toute sécurité en utilisant la biométrie Android.",
            androidLoginButton: "Utiliser la connexion Android",
            android: "Android",
            usbLoginTitle: "Clé de sécurité USB",
            usbLoginMessage: "Connectez-vous avec votre clé de sécurité USB.",
            usbLoginButton: "Utiliser la clé de sécurité USB",
            usb: "USB",
            smsLoginTitle: "Connexion par SMS",
            smsLoginMessage: "Connectez-vous en utilisant un code à usage unique envoyé par SMS.",
            smsLoginButton: "Utiliser la connexion par SMS",
            sms: "SMS",
            smsLoginChangePhoneTitle: "Changer de numéro de téléphone",
            smsLoginChangePhoneMessage: "Entrez un nouveau numéro de téléphone pour recevoir votre code SMS.",
            smsLoginChangePhoneInputLabel: "Nouveau numéro de téléphone",
            smsLoginChangePhoneButton: "Mettre à jour le numéro de téléphone",
            smsLoginPinTitle: "PIN SMS",
            smsLoginPinMessage: "Entrez le PIN envoyé à votre téléphone.",
            smsLoginPinButton: "Soumettre le PIN",
            loginWelcomeTitle: "Bon retour!",
            loginWelcomeSubtitleSubtitle: "Connectez-vous en toute sécurité à votre compte.",
            loginWelcomeKnownUserSubtitle: "Bienvenue, {username}! Prêt à continuer?",
            registerNewQuickLoginTitle: "Connexion rapide",
            registerNewQuickLoginTitleWithSocial: "Ou inscrivez-vous avec votre compte social:",
            registerNewQuickLoginSubtitle: "Complétez le processus d'inscription rapide pour commencer.",
            phoneIsRequired: "Le numéro de téléphone est requis.",
            phoneIsInvalid: "Le numéro de téléphone est invalide.",
            forceEnrollMfaTitle: "Inscription à MFA",
            forceEnrollMfaSubtitle: "Vous devez activer l'authentification à plusieurs facteurs pour continuer.",
            forceEnrollMfaAuthenticatorApp: "Utiliser une application d'authentification",
            forceEnrollMfaAuthenticatorAppDescription: "Scannez le code QR avec votre application d'authentification.",
            forceEnrollMfaSMS: "Utiliser SMS",
            forceEnrollMfaPlatform: "Utiliser la sécurité basée sur la plateforme",
            forceEnrollMfaCrossPlatform: "MFA multiplateforme",
            forceEnrollMfaCrossPlatformDescription: "Connectez-vous en toute sécurité avec une méthode multiplateforme.",
            preEnrollMfaSMSTitle: "Inscription via SMS",
            preEnrollMfaSMSSubtitle: "Configurez l'authentification à plusieurs facteurs basée sur SMS.",
            preEnrollMfaSMSSubmitButtonMessage: "Soumettre",
            mfaSMSTitle: "Authentification à plusieurs facteurs par SMS",
            mfaSMSSubtitle: "Entrez le code envoyé à votre téléphone.",
            mfaSMSResendCode: "Renvoyer le code",
            enrollMfaSMSBackMessage: "Retour",
            moreWaysToAuthenticate: "Plus de moyens de s'authentifier",
            loginMfaSMS: "Connexion via SMS",
            loginMfaSMSDescription: "Entrez le code envoyé à votre téléphone.",
            loginMfaPlatform: "Utiliser la sécurité de la plateforme",
            loginMfaPlatformDescription: "Connectez-vous avec la sécurité basée sur la plateforme.",
            loginMfaCrossPlatform: "MFA multiplateforme",
            loginMfaCrossPlatformDescription: "Connectez-vous en utilisant la sécurité multiplateforme.",
            loginMfaAuthenticatorApp: "Utiliser l'application d'authentification",
            loginMfaAuthenticatorAppDescription: "Entrez le code de votre application d'authentification.",
            loginMfaAuthenticatorAppTitle: "Connexion avec l'application d'authentification",
            loginMfaHelpMessage: "Besoin d'aide avec l'authentification à plusieurs facteurs?",
            useRecoveryCode: "Utiliser le code de récupération",
          }
        }
      },
      de: {
        loginBox: {
          login: {
            title: "Anmelden",
            signUpMessage: "Noch keinen Account? Hier registrieren.",
            signUpLink: "Ein neues Konto erstellen",
            forgotPassword: "Passwort vergessen?",
            emailInputLabel: "E-Mail-Adresse",
            emailInputPlaceholder: "name@beispiel.com",
            emailMustBeValid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
            emailIsRequired: "E-Mail-Adresse ist erforderlich.",
            passwordInputLabel: "Passwort",
            passwordInputPlaceholder: "Geben Sie Ihr Passwort ein",
            passwordMustBeCharacters: "Das Passwort muss mindestens 8 Zeichen lang sein.",
            passwordIsRequired: "Passwort ist erforderlich.",
            login: "Anmelden",
            continue: "Fortfahren",
            invalidTitle: "Ungültiger Anmeldeversuch",
            signInWithSocialLogin: "Oder melden Sie sich an mit:",
            backToLogin: "Zurück zur Anmeldung",
            mfaTitle: "Multi-Faktor-Authentifizierung",
            mfaSubtitle: "Bitte geben Sie den Code ein, der an Ihr Gerät gesendet wurde.",
            mfaAuthenticatorTitle: "Authentifikator-Code",
            mfaInputLabel: "Geben Sie den MFA-Code ein",
            mfaCodeIsRequired: "MFA-Code ist erforderlich.",
            mfaCodeLengthAtLeast6: "MFA-Code muss mindestens 6 Ziffern lang sein.",
            twoFactorCodeIsRequired: "Zwei-Faktor-Code ist erforderlich.",
            twoFactorCodeLengthAtLeast8: "Zwei-Faktor-Code muss mindestens 8 Ziffern lang sein.",
            mfaRememberThisDevice: "Dieses Gerät für zukünftige Anmeldungen merken.",
            mfaRememberLongerThenYear: "Ein Jahr oder länger angemeldet bleiben.",
            disableMultiFactorTitle: "MFA deaktivieren",
            disableMultiFactorMessage: "Sind Sie sicher, dass Sie die Multi-Faktor-Authentifizierung deaktivieren möchten?",
            recoverMfaTitle: "Multi-Faktor-Authentifizierung wiederherstellen",
            recoverMfaMessage: "Geben Sie Ihren Wiederherstellungscode ein, um wieder Zugriff zu erhalten.",
            disabledMultiFactorClickHereButton: "Klicken Sie hier, um MFA wiederherzustellen.",
            enterRecoveryCode: "Geben Sie Ihren Wiederherstellungscode ein",
            disabledMultiFactorButton: "MFA wiederherstellen",
            missingPolicyErrorMessage: "Ihre Anmelderichtlinie enthält nicht die erforderlichen Konfigurationen.",
            magicLinkTitle: "Magischer Link gesendet",
            magicLinkText: "Überprüfen Sie Ihre E-Mails, um sich mit dem magischen Link anzumelden.",
            magicLinkResend: "Magischen Link erneut senden",
            magicLinkResending: "Magischer Link wird erneut gesendet...",
            invalidMagicLinkTitle: "Ungültiger magischer Link",
            invalidMagicLinkText: "Der magische Link, den Sie verwendet haben, ist ungültig oder abgelaufen.",
            smsOtcTitle: "Einmaliger SMS-Code",
            smsOtcMessage: "Bitte geben Sie den einmaligen Code ein, der an Ihr Telefon gesendet wurde.",
            smsOtcChangePhoneMessage: "Telefonnummer ändern?",
            otcTitle: "Einmaliger Code",
            otcMessage: "Geben Sie den an Ihr Gerät gesendeten Code ein.",
            otcInputLabel: "Geben Sie den Code ein",
            otcInputPlaceholder: "123456",
            otcCodeIsRequired: "Einmaliger Code ist erforderlich.",
            otcContinue: "Bestätigen",
            otcHaventReceivedCode: "Code nicht erhalten?",
            otcResend: "Code erneut senden",
            otcResending: "Code wird erneut gesendet...",
            otcInvalidLengthCode: "Der Code muss genau 6 Ziffern lang sein.",
            ssoRedirectToMessage: "Weiterleitung zu Ihrem SSO-Anbieter...",
            failedOicdLoginTitle: "Anmeldung fehlgeschlagen",
            failedOicdBackToLogin: "Zurück zur Anmeldung",
            failedSamlDefaultError: "Es gab einen Fehler beim SAML-Login.",
            failedSamlBackToLogin: "Zurück zur Anmeldung",
            joinTenantTitle: "Organisation beitreten",
            failedJoinTenantTitle: "Beitritt zur Organisation fehlgeschlagen",
            failedJoinTenantBackButton: "Zurück zum Beitrittsbildschirm",
            forceMfaTitle: "MFA erzwingen",
            forceMfaMessage: "Sie müssen die Multi-Faktor-Authentifizierung aktivieren, um fortzufahren.",
            forceMfaScanQueryDescription1: "Scannen Sie den QR-Code mit Ihrer Authentifikator-App.",
            forceMfaScanQueryDescription2: "Geben Sie dann den Bestätigungscode ein, um fortzufahren.",
            forceMfaInputLabel: "Bestätigungscode eingeben",
            forceMfaInputPlaceholder: "123456",
            forceMfaVerifyButton: "Bestätigen",
            forceMfaRememberThisDevice: "Dieses Gerät merken",
            forceMfaRememberLongerThenYear: "Ein Jahr angemeldet bleiben",
            disclaimerText: "Ich stimme den",
            termsLinkText: "Nutzungsbedingungen",
            termsLink: "/bedingungen",
            privacyLinkText: "Datenschutzbestimmungen",
            privacyLink: "/datenschutz",
            termsAndPrivacyConjunctionText: "und",
            oneTouchLoginTitle: "One-Touch-Anmeldung",
            oneTouchLoginMessage: "Melden Sie sich sicher mit einem Klick an.",
            oneTouchLoginButton: "One-Touch-Anmeldung verwenden",
            touchId: "Mit Touch ID anmelden",
            androidLoginTitle: "Android-Anmeldung",
            androidLoginMessage: "Melden Sie sich sicher mit der Android-Biometrie an.",
            androidLoginButton: "Android-Anmeldung verwenden",
            android: "Android",
            usbLoginTitle: "USB-Sicherheitsschlüssel",
            usbLoginMessage: "Melden Sie sich mit Ihrem USB-Sicherheitsschlüssel an.",
            usbLoginButton: "USB-Sicherheitsschlüssel verwenden",
            usb: "USB",
            smsLoginTitle: "SMS-Anmeldung",
            smsLoginMessage: "Melden Sie sich mit einem einmaligen Code an, der per SMS gesendet wurde.",
            smsLoginButton: "SMS-Anmeldung verwenden",
            sms: "SMS",
            smsLoginChangePhoneTitle: "Telefonnummer ändern",
            smsLoginChangePhoneMessage: "Geben Sie eine neue Telefonnummer ein, um Ihren SMS-Code zu erhalten.",
            smsLoginChangePhoneInputLabel: "Neue Telefonnummer",
            smsLoginChangePhoneButton: "Telefonnummer aktualisieren",
            smsLoginPinTitle: "SMS-PIN",
            smsLoginPinMessage: "Geben Sie die PIN ein, die an Ihr Telefon gesendet wurde.",
            smsLoginPinButton: "PIN senden",
            loginWelcomeTitle: "Willkommen zurück!",
            loginWelcomeSubtitleSubtitle: "Melden Sie sich sicher bei Ihrem Konto an.",
            loginWelcomeKnownUserSubtitle: "Willkommen, {username}! Bereit, weiterzumachen?",
            registerNewQuickLoginTitle: "Schnelle Anmeldung",
            registerNewQuickLoginTitleWithSocial: "Oder melden Sie sich mit Ihrem sozialen Konto an:",
            registerNewQuickLoginSubtitle: "Vervollständigen Sie den schnellen Anmeldeprozess, um loszulegen.",
            phoneIsRequired: "Telefonnummer ist erforderlich.",
            phoneIsInvalid: "Telefonnummer ist ungültig.",
            forceEnrollMfaTitle: "MFA aktivieren",
            forceEnrollMfaSubtitle: "Sie müssen die Multi-Faktor-Authentifizierung aktivieren, um fortzufahren.",
            forceEnrollMfaAuthenticatorApp: "Verwenden Sie eine Authentifikator-App",
            forceEnrollMfaAuthenticatorAppDescription: "Scannen Sie den QR-Code mit Ihrer Authentifikator-App.",
            forceEnrollMfaSMS: "Verwenden Sie SMS",
            forceEnrollMfaPlatform: "Verwenden Sie plattformbasierte Sicherheit",
            forceEnrollMfaCrossPlatform: "Plattformübergreifende MFA",
            forceEnrollMfaCrossPlatformDescription: "Melden Sie sich sicher mit einer plattformübergreifenden Methode an.",
            preEnrollMfaSMSTitle: "Per SMS anmelden",
            preEnrollMfaSMSSubtitle: "Richten Sie die SMS-basierte Multi-Faktor-Authentifizierung ein.",
            preEnrollMfaSMSSubmitButtonMessage: "Senden",
            mfaSMSTitle: "Multi-Faktor-Authentifizierung per SMS",
            mfaSMSSubtitle: "Geben Sie den an Ihr Telefon gesendeten Code ein.",
            mfaSMSResendCode: "Code erneut senden",
            enrollMfaSMSBackMessage: "Zurück",
            moreWaysToAuthenticate: "Weitere Authentifizierungsmethoden",
            loginMfaSMS: "Anmeldung per SMS",
            loginMfaSMSDescription: "Geben Sie den an Ihr Telefon gesendeten Code ein.",
            loginMfaPlatform: "Plattformbasierte Sicherheit verwenden",
            loginMfaPlatformDescription: "Melden Sie sich mit plattformbasierter Sicherheit an.",
            loginMfaCrossPlatform: "Plattformübergreifende MFA",
            loginMfaCrossPlatformDescription: "Melden Sie sich mit plattformübergreifender Sicherheit an.",
            loginMfaAuthenticatorApp: "Authentifikator-App verwenden",
            loginMfaAuthenticatorAppDescription: "Geben Sie den Code Ihrer Authentifikator-App ein.",
            loginMfaAuthenticatorAppTitle: "Anmeldung mit Authentifikator-App",
            loginMfaHelpMessage: "Hilfe bei der Multi-Faktor-Authentifizierung benötigt?",
            useRecoveryCode: "Wiederherstellungscode verwenden",
          }
        }
      },
      it: {
        loginBox: {
          login: {
            title: "Accedi",
            signUpMessage: "Non hai un account? Registrati qui.",
            signUpLink: "Crea un nuovo account",
            forgotPassword: "Hai dimenticato la password?",
            emailInputLabel: "Indirizzo email",
            emailInputPlaceholder: "nome@esempio.com",
            emailMustBeValid: "Inserisci un indirizzo email valido.",
            emailIsRequired: "L'indirizzo email è obbligatorio.",
            passwordInputLabel: "Password",
            passwordInputPlaceholder: "Inserisci la tua password",
            passwordMustBeCharacters: "La password deve contenere almeno 8 caratteri.",
            passwordIsRequired: "La password è obbligatoria.",
            login: "Accedi",
            continue: "Continua",
            invalidTitle: "Tentativo di accesso non valido",
            signInWithSocialLogin: "Oppure accedi con:",
            backToLogin: "Torna all'accesso",
            mfaTitle: "Autenticazione multi-fattore",
            mfaSubtitle: "Inserisci il codice inviato al tuo dispositivo.",
            mfaAuthenticatorTitle: "Codice dell'autenticatore",
            mfaInputLabel: "Inserisci il codice MFA",
            mfaCodeIsRequired: "Il codice MFA è obbligatorio.",
            mfaCodeLengthAtLeast6: "Il codice MFA deve contenere almeno 6 cifre.",
            twoFactorCodeIsRequired: "Il codice a due fattori è obbligatorio.",
            twoFactorCodeLengthAtLeast8: "Il codice a due fattori deve contenere almeno 8 cifre.",
            mfaRememberThisDevice: "Ricorda questo dispositivo per i futuri accessi.",
            mfaRememberLongerThenYear: "Mantieni l'accesso per un anno o più.",
            disableMultiFactorTitle: "Disabilita MFA",
            disableMultiFactorMessage: "Sei sicuro di voler disabilitare l'autenticazione multi-fattore?",
            recoverMfaTitle: "Recupera l'autenticazione multi-fattore",
            recoverMfaMessage: "Inserisci il tuo codice di recupero per riottenere l'accesso.",
            disabledMultiFactorClickHereButton: "Clicca qui per recuperare MFA.",
            enterRecoveryCode: "Inserisci il tuo codice di recupero",
            disabledMultiFactorButton: "Recupera MFA",
            missingPolicyErrorMessage: "La tua politica di accesso manca delle configurazioni richieste.",
            magicLinkTitle: "Link magico inviato",
            magicLinkText: "Controlla la tua email per accedere utilizzando il link magico.",
            magicLinkResend: "Reinvia link magico",
            magicLinkResending: "Reinvio del link magico in corso...",
            invalidMagicLinkTitle: "Link magico non valido",
            invalidMagicLinkText: "Il link magico che hai usato è non valido o è scaduto.",
            smsOtcTitle: "Codice SMS usa e getta",
            smsOtcMessage: "Inserisci il codice usa e getta inviato al tuo telefono.",
            smsOtcChangePhoneMessage: "Cambiare il numero di telefono?",
            otcTitle: "Codice usa e getta",
            otcMessage: "Inserisci il codice inviato al tuo dispositivo.",
            otcInputLabel: "Inserisci il codice",
            otcInputPlaceholder: "123456",
            otcCodeIsRequired: "Il codice usa e getta è obbligatorio.",
            otcContinue: "Verifica",
            otcHaventReceivedCode: "Non hai ricevuto il codice?",
            otcResend: "Reinvia codice",
            otcResending: "Reinvio del codice in corso...",
            otcInvalidLengthCode: "Il codice deve contenere esattamente 6 cifre.",
            ssoRedirectToMessage: "Reindirizzamento al tuo provider SSO...",
            failedOicdLoginTitle: "Accesso fallito",
            failedOicdBackToLogin: "Torna all'accesso",
            failedSamlDefaultError: "Si è verificato un errore durante l'accesso SAML.",
            failedSamlBackToLogin: "Torna all'accesso",
            joinTenantTitle: "Unisci all'organizzazione",
            failedJoinTenantTitle: "Unione all'organizzazione fallita",
            failedJoinTenantBackButton: "Torna alla schermata di unione",
            forceMfaTitle: "Forza MFA",
            forceMfaMessage: "Devi abilitare l'autenticazione multi-fattore per procedere.",
            forceMfaScanQueryDescription1: "Scansiona il codice QR con la tua app autenticatrice.",
            forceMfaScanQueryDescription2: "Poi, inserisci il codice di verifica per continuare.",
            forceMfaInputLabel: "Inserisci il codice di verifica",
            forceMfaInputPlaceholder: "123456",
            forceMfaVerifyButton: "Verifica",
            forceMfaRememberThisDevice: "Ricorda questo dispositivo",
            forceMfaRememberLongerThenYear: "Mantieni l'accesso per un anno",
            disclaimerText: "Accetto i",
            termsLinkText: "Termini di servizio",
            termsLink: "/termini",
            privacyLinkText: "Politica sulla privacy",
            privacyLink: "/privacy",
            termsAndPrivacyConjunctionText: "e",
            oneTouchLoginTitle: "Accesso con un tocco",
            oneTouchLoginMessage: "Accedi in modo sicuro con un solo tocco.",
            oneTouchLoginButton: "Usa l'accesso con un tocco",
            touchId: "Accedi con Touch ID",
            androidLoginTitle: "Accesso Android",
            androidLoginMessage: "Accedi in modo sicuro utilizzando la biometria di Android.",
            androidLoginButton: "Usa l'accesso Android",
            android: "Android",
            usbLoginTitle: "Chiave di sicurezza USB",
            usbLoginMessage: "Accedi con la tua chiave di sicurezza USB.",
            usbLoginButton: "Usa la chiave di sicurezza USB",
            usb: "USB",
            smsLoginTitle: "Accesso SMS",
            smsLoginMessage: "Accedi utilizzando un codice usa e getta inviato via SMS.",
            smsLoginButton: "Usa l'accesso SMS",
            sms: "SMS",
            smsLoginChangePhoneTitle: "Cambia numero di telefono",
            smsLoginChangePhoneMessage: "Inserisci un nuovo numero di telefono per ricevere il codice SMS.",
            smsLoginChangePhoneInputLabel: "Nuovo numero di telefono",
            smsLoginChangePhoneButton: "Aggiorna numero di telefono",
            smsLoginPinTitle: "PIN SMS",
            smsLoginPinMessage: "Inserisci il PIN inviato al tuo telefono.",
            smsLoginPinButton: "Invia PIN",
            loginWelcomeTitle: "Bentornato!",
            loginWelcomeSubtitleSubtitle: "Accedi in modo sicuro al tuo account.",
            loginWelcomeKnownUserSubtitle: "Benvenuto, {username}! Pronto a continuare?",
            registerNewQuickLoginTitle: "Accesso rapido",
            registerNewQuickLoginTitleWithSocial: "Oppure registrati con il tuo account social:",
            registerNewQuickLoginSubtitle: "Completa il processo di registrazione rapida per iniziare.",
            phoneIsRequired: "Il numero di telefono è obbligatorio.",
            phoneIsInvalid: "Il numero di telefono è non valido.",
            forceEnrollMfaTitle: "Abilita MFA",
            forceEnrollMfaSubtitle: "Devi abilitare l'autenticazione multi-fattore per continuare.",
            forceEnrollMfaAuthenticatorApp: "Usa un'app autenticatrice",
            forceEnrollMfaAuthenticatorAppDescription: "Scansiona il codice QR con la tua app autenticatrice.",
            forceEnrollMfaSMS: "Usa SMS",
            forceEnrollMfaPlatform: "Usa sicurezza basata sulla piattaforma",
            forceEnrollMfaCrossPlatform: "MFA multipiattaforma",
            forceEnrollMfaCrossPlatformDescription: "Accedi in modo sicuro con un metodo multipiattaforma.",
            preEnrollMfaSMSTitle: "Iscriviti via SMS",
            preEnrollMfaSMSSubtitle: "Configura l'autenticazione multi-fattore basata su SMS.",
            preEnrollMfaSMSSubmitButtonMessage: "Invia",
            mfaSMSTitle: "Autenticazione multi-fattore via SMS",
            mfaSMSSubtitle: "Inserisci il codice inviato al tuo telefono.",
            mfaSMSResendCode: "Reinvia codice",
            enrollMfaSMSBackMessage: "Indietro",
            moreWaysToAuthenticate: "Altri modi per autenticarsi",
            loginMfaSMS: "Accesso via SMS",
            loginMfaSMSDescription: "Inserisci il codice inviato al tuo telefono.",
            loginMfaPlatform: "Usa sicurezza della piattaforma",
            loginMfaPlatformDescription: "Accedi con la sicurezza basata sulla piattaforma.",
            loginMfaCrossPlatform: "MFA multipiattaforma",
            loginMfaCrossPlatformDescription: "Accedi utilizzando sicurezza multipiattaforma.",
            loginMfaAuthenticatorApp: "Usa l'app autenticatrice",
            loginMfaAuthenticatorAppDescription: "Inserisci il codice della tua app autenticatrice.",
            loginMfaAuthenticatorAppTitle: "Accesso con l'app autenticatrice",
            loginMfaHelpMessage: "Hai bisogno di aiuto con l'autenticazione multi-fattore?",
            useRecoveryCode: "Usa codice di recupero",
          }
        }
      }
    }
  });
});

async function startServer() {
  try {
    if (useNgrok) {
      const url = await ngrok.connect(port);
      console.log(`ngrok tunnel established at ${url}`);
    } else {
      console.log(`Server is running on http://localhost:${port}`);
    }
    app.listen(port);
  } catch (err) {
    console.error('Error starting ngrok:', err);
  }
}

startServer();
